default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000
  username: <%= ENV.fetch("POSTGRES_USER", "mindfulme") %>
  password: <%= ENV.fetch("POSTGRES_PASSWORD", "mindfulmeapp-2024") %>
  host: <%= ENV.fetch("POSTGRES_HOST", "localhost") %>

development:
  <<: *default
  database: <%= ENV.fetch("POSTGRES_DB", "mindfulme_development") %>

test:
  <<: *default
  database: <%= ENV.fetch("POSTGRES_DB", "mindfulme_test") %>

production:
  <<: *default
  database: <%= ENV.fetch("POSTGRES_DB", "mindfulme_production") %>
  username: <%= ENV.fetch("POSTGRES_USER", "mindfulme") %>
  password: <%= ENV.fetch("POSTGRES_PASSWORD", "mindfulmeapp-2024") %>
